#!/bin/sh
echo Starting ServerEach in /opt/servereach/
trap '' 1
LANG=
export LANG
#PERLIO=:raw
unset PERLIO
export PERLIO
PERLLIB=/usr/libexec/webmin
export PERLLIB
exec '/opt/servereach/miniserv.pl' /opt/servereach/miniserv.conf
